.TH "XCopy User Manual" 0.20180525 "25 May 2018" "XCopy documentation"

.SH NAME
xcopy

.SH DESCRIPTION
Bash-script for copy dir as sort structure.

.SH SYNOPSIS
xcopy [options] srcdir destdir

.SH OPTIONS
.TP
-l
hardlink files
.TP
-n
no copy files (only directory)
.TP
-h
help

.SH EXAMPLE
 xcopy /path/to/my/files tmp

.SH COPYRIGHT
Copyright 2015 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 cpio,
 find,
 sort,
 ln

.SH CONTACTS
 Website: https://github.com/zvezdochiot/bash-xcopy
 Email: zvezdochiot@users.sourceforge.net
